version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/chd-qbank"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 5
    labels: ["dependencies"]
    groups:
      production-dependencies:
        dependency-type: "production"
      development-toolkits:
        dependency-type: "development"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
    labels: ["dependencies"]
    groups:
      workflow-automation:
        patterns:
          - "*"
