version: "3.9"

services:
  qbank-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL:-}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY:-}
    environment:
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL:-}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY:-}
      SUPABASE_URL: ${SUPABASE_URL:-}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY:-}
    ports:
      - "3000:80"
