version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL:-}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY:-}
      SUPABASE_URL: ${SUPABASE_URL:-}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY:-}
    ports:
      - "5173:5173"
    volumes:
      - .:/workspace
      - node_modules_root:/workspace/node_modules
      - node_modules_app:/workspace/chd-qbank/node_modules

volumes:
  node_modules_root:
  node_modules_app:
