name: chd-qbank PR checks

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'chd-qbank/**'
      - '.github/workflows/chd-qbank-pr.yml'
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

permissions:
  contents: read

# cancel older runs on the same PR branch
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  install-lint-build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: chd-qbank
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a25f0e4a72 # v4.1.6

      - name: Setup Node.js
        uses: actions/setup-node@5e21ff4d9f0f45a73d87940c49aa5addf5328d0f # v4.0.2
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: chd-qbank/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present -- --max-warnings=0

      - name: Type check
        run: npm run typecheck --if-present

      - name: Build
        run: npm run build
