name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chd-qbank
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a25f0e4a72 # v4.1.6
      - uses: actions/setup-node@5e21ff4d9f0f45a73d87940c49aa5addf5328d0f # v4.0.2
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'chd-qbank/package-lock.json'
      - uses: dorny/paths-filter@8d6a028232b48cf9449877dc87aef5d30daeb4c3 # v3.0.2
        id: changes
        with:
          filters: |
            migrations:
              - 'chd-qbank/supabase/migrations/**'
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test -- --run --reporter=dot
      - run: npm run build
      - run: npm run notice
      - name: Generate SBOM (CycloneDX)
        run: |
          mkdir -p compliance-artifacts
          npx --yes @cyclonedx/cyclonedx-npm --output-file compliance-artifacts/chd-qbank-cyclonedx.json --output-format json
      - name: Capture npm audit report
        run: |
          mkdir -p compliance-artifacts
          npm audit --json > compliance-artifacts/npm-audit.json || true
      - name: Upload compliance artifacts
        uses: actions/upload-artifact@65403d292b69ca99566f9f8213238b1462f9aa0e # v4.3.3
        with:
          name: compliance-artifacts
          path: chd-qbank/compliance-artifacts
      - name: Check Supabase migration safety
        if: steps.changes.outputs.migrations == 'true'
        run: npm run check:migration-safety
      - name: Ensure NOTICE and license inventory are current
        working-directory: ..
        run: git diff --exit-code

  edge-function-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chd-qbank/supabase/functions/signup-with-code
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a25f0e4a72 # v4.1.6
      - uses: denoland/setup-deno@db94c30a7d69dbab71c373b72ed9d6d8d3e15794 # v1.1.1
        with:
          deno-version: v1.x
      - run: deno lint
      - run: deno check index.ts
