name: E2E (pull request)

on:
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chd-qbank
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'chd-qbank/package-lock.json'
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Run Playwright tests against staging
        env:
          BASE_URL: ${{ secrets.STAGING_URL }}
          INVITE_CODE: ${{ secrets.STAGING_INVITE }}
        run: npm run test:e2e
