name: E2E (pull request)

on:
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chd-qbank
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a25f0e4a72 # v4.1.6
      - uses: actions/setup-node@5e21ff4d9f0f45a73d87940c49aa5addf5328d0f # v4.0.2
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'chd-qbank/package-lock.json'
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Run Playwright tests against staging
        env:
          BASE_URL: ${{ secrets.STAGING_URL }}
          INVITE_CODE: ${{ secrets.STAGING_INVITE }}
        run: npm run test:e2e
