name: Secret Scan (gitleaks)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for accurate scan)
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a25f0e4a72 # v4.1.6
        with:
          fetch-depth: 0

      - name: Run gitleaks (fail on findings, redact output)
        uses: zricethezav/gitleaks@c4d3b3bd2d96ff47568cf8127781d78b810e16a3 # v8.18.4
        with:
          args: detect --source . --redact --exit-code 1
