name: Secret Scan (gitleaks)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout (full history for accurate scan)
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a25f0e4a72 # v4.1.6
        with:
          fetch-depth: 0

      - name: Install gitleaks
        run: |
          GL_VERSION=8.18.4
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v${GL_VERSION}/gitleaks_${GL_VERSION}_linux_x64.tar.gz \
            | tar -xz gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks
          gitleaks version

      - name: Run gitleaks (fail on findings, redact output)
        run: gitleaks detect --source . --redact --exit-code 1 --config .gitleaks.toml
