name: Validate QBank
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci || npm i
        working-directory: chd-qbank
      - run: npm test
        working-directory: chd-qbank
