name: Validate QBank

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'chd-qbank/**'
      - '.github/workflows/validate-qbank.yml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: chd-qbank
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a25f0e4a72 # v4.1.6
      - uses: actions/setup-node@5e21ff4d9f0f45a73d87940c49aa5addf5328d0f # v4.0.2
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "chd-qbank/package-lock.json"
      - run: npm ci
      - run: npm test -- --run --reporter=dot
